[package]
name = "notes-manager"
version = "0.1.0"
edition = "2024"
default-run = "notes-manager" 

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.225", features = ["derive"] }
